### ISSUE TITLE
API point for Fabric API

### ISSUE THREAD

**Issue by DeathsGun** [FabricMC/fabric-meta#2]
Would be great to have also access to the latest versions of the API.
Like this:
```
/v1/versions/api
```
```
/v1/versions/api/:game_version
```

**Comment by modmuss50** [comment]
Possibly, this may need to come after we have finished splitting it all up into modules

**Comment by DeathsGun** [comment]
okay thanks

**Comment by modmuss50** [comment]
I dont think this will happen, as fabric api is just a mod, this meta api is just for launching/installing meta.
