### ISSUE TITLE
Cache issue on /v2/versions/game

### ISSUE THREAD

**Issue by JulianVennen** [FabricMC/fabric-meta#22]
The endpoint /v2/versions/game sometimes shows 23w06a and sometimes not.
This is looks like a cache issue to me.

**Comment by modmuss50** [comment]
Hi, the Mojang CDN has been having major issues the past few days. It seems depending on which node you (or the fabric meta server) access depends if you get the snapshot or not.

I dont think there is much we can do about this, easily.

**Comment by JulianVennen** [comment]
Interesting, we also query piston-meta from the same domain and don't get any such weird behavior from it.

**Comment by JulianVennen** [comment]
Seems like it's stable, even with the new snapshot.
